/** Compatibility facade. Canonical wire/domain schemas and inferred types live in @vibe/protocol. */
export type {
  Mode,
  Role,
  Part,
  TaskStatus,
  Task,
  ModelSummary,
  ProviderInfo,
  AgentInfo,
  AgentCapability,
  GoalContract,
  PlanState,
  QuestionChoice,
  StructuredQuestion,
  ActivityInfo,
  SkillInfo,
  QueuedItem,
  Usage,
  SessionUsage,
  Message,
  GitInfo,
  JobInfo,
  GoalRunInfo,
  EngineSnapshot,
} from "@vibe/protocol";
