import { afterEach, describe, expect, it, vi } from "vitest";
import { EngineEventCoalescer } from "./event-coalescer";
describe("EngineEventCoalescer", () => {
  afterEach(() => vi.useRealTimers());
  it("forwards first immediately and concatenates the burst", () => { vi.useFakeTimers(); const events: unknown[] = []; const value = new EngineEventCoalescer((event) => events.push(event)); value.push({ type: "assistant-text-delta", sessionId: "ses-a", delta: "a" }); value.push({ type: "assistant-text-delta", sessionId: "ses-a", delta: "b" }); value.push({ type: "assistant-text-delta", sessionId: "ses-a", delta: "c" }); expect(events).toHaveLength(1); vi.advanceTimersByTime(12); expect(events).toEqual([{ type: "assistant-text-delta", sessionId: "ses-a", delta: "a" }, { type: "assistant-text-delta", sessionId: "ses-a", delta: "bc" }]); });
  it("flushes before boundaries", () => { const events: unknown[] = []; const value = new EngineEventCoalescer((event) => events.push(event)); value.push({ type: "reasoning-delta", sessionId: "ses-a", delta: "a" }); value.push({ type: "reasoning-delta", sessionId: "ses-a", delta: "b" }); value.push({ type: "turn-finished", sessionId: "ses-a" }); expect(events).toHaveLength(3); });
  it("keeps subagent and tool identities separate", () => { const events: unknown[] = []; const value = new EngineEventCoalescer((event) => events.push(event)); value.push({ type: "reasoning-delta", sessionId: "ses-a", subagentId: "one", delta: "a" }); value.push({ type: "reasoning-delta", sessionId: "ses-a", subagentId: "two", delta: "b" }); value.push({ type: "tool-call-progress", sessionId: "ses-a", toolCallId: "one", chunk: "c" }); value.push({ type: "tool-call-progress", sessionId: "ses-a", toolCallId: "two", chunk: "d" }); value.flush(); expect(events).toHaveLength(4); });
  it("cuts a synthetic high-chunk stream by well over sixty percent", () => { vi.useFakeTimers(); const events: unknown[] = []; const value = new EngineEventCoalescer((event) => events.push(event)); for (let index = 0; index < 1_000; index += 1) value.push({ type: "assistant-text-delta", sessionId: "ses-a", delta: "x" }); vi.advanceTimersByTime(12); expect(events).toHaveLength(2); expect(events.map((event) => (event as { delta: string }).delta).join("")).toHaveLength(1_000); });
  it("caps a continuous burst from its first delta", () => { vi.useFakeTimers(); const events: unknown[] = []; const value = new EngineEventCoalescer((event) => events.push(event)); value.push({ type: "assistant-text-delta", sessionId: "ses-a", delta: "a" }); vi.advanceTimersByTime(5); value.push({ type: "assistant-text-delta", sessionId: "ses-a", delta: "b" }); vi.advanceTimersByTime(7); expect(events).toHaveLength(2); });
});
